"""The two recorded workspaces, loaded from contracts/fixtures.

`sandbox.json` is a recording of a real pipeline run, regenerated by
`scripts/seed_fixtures.py`. `mit.json` describes published audit reports whose
source is a PDF hosted elsewhere, so it cannot be regenerated here.

Every other workspace is derived from committed records by `app/projection.py`,
which is also the only module that builds a Bundle. This one keeps the recorded
pair readable and lets a reviewer decide an approval on them.
"""

from __future__ import annotations

import json
import threading
from pathlib import Path

from .models import ApprovalStatus, Bundle, WorkspaceId

FIXTURES = Path(__file__).resolve().parents[2] / "contracts" / "fixtures"

_bundles: dict[str, dict] = {}

# Specialists may investigate concurrently (spec.md §8), so anything that mutates
# a bundle takes this. Reads stay lock-free: they validate a snapshot of the dict.
_lock = threading.Lock()


def _load(ws: WorkspaceId) -> dict:
    return json.loads((FIXTURES / f"{ws}.json").read_text(encoding="utf-8"))


def get_bundle(ws: WorkspaceId) -> Bundle:
    if ws not in _bundles:
        _bundles[ws] = _load(ws)
    return Bundle.model_validate(_bundles[ws])


def reset(ws: WorkspaceId | None = None) -> None:
    if ws is None:
        _bundles.clear()
    else:
        _bundles.pop(ws, None)


def decide_approval(ws: WorkspaceId, approval_id: str, decision: ApprovalStatus) -> Bundle:
    """Human decision. Agents may never call this path (spec.md §8)."""
    with _lock:
        bundle = _bundles.setdefault(ws, _load(ws))
        found = False
        for approval in bundle["approvals"]:
            if approval["id"] == approval_id:
                approval["status"] = decision
                found = True
        if not found:
            raise KeyError(approval_id)
        if decision == "approved":
            for task in bundle["tasks"]:
                if task.get("approval_id") == approval_id:
                    task["column"] = "done"
                    task["progress"] = 100
        return Bundle.model_validate(bundle)
